<?php
declare(strict_types=1);
if (PHP_SAPI!=='cli') exit;
require __DIR__.'/../app/Core/bootstrap.php';
require __DIR__.'/../app/Services/ClientCheckout.php';
require __DIR__.'/temporary-store-promotions.php';
$db=conectarBaseDatos();temporaryStorePromotions($db);
foreach (['cuentas','clientes','categorias_productos','productos','ventas','detalle_ventas','pagos','tarjetas_regalo','movimientos_tarjetas_regalo','tarjetas_regalo_clientes'] as $table) temporaryStoreTable($db,$table);
$db->exec("INSERT INTO cuentas (id_cuenta,id_rol,usuario,correo,correo_verificado,contrasena_hash) VALUES (1,1,'gift_a','a@test.invalid',1,'test'),(2,1,'gift_b','b@test.invalid',0,'test')");
$db->exec("UPDATE cuentas SET estado='activo'");
$db->exec("INSERT INTO clientes (id_cliente,id_cuenta,nombre,apellidos) VALUES (1,1,'Ana','Test'),(2,2,'Luis','Test')");
$db->exec("INSERT INTO categorias_productos (id_categoria_producto,nombre,activo) VALUES (1,'Test',1)");
$db->exec("INSERT INTO productos (id_producto,id_categoria_producto,sku,nombre,precio,stock_actual,activo) VALUES (1,1,'GIFT-TEST','Test',1000,20,1)");
$insert=$db->prepare("INSERT INTO tarjetas_regalo (id_tarjeta,codigo_hash,id_cliente_comprador,nombre_destinatario,correo_destinatario,monto_inicial,estado) VALUES (?,?,1,'Test',?,?,'activa')");
foreach ([1=>['a@test.invalid',5000],2=>['b@test.invalid',500],3=>['other@test.invalid',1000],4=>['other@test.invalid',1000]] as $id=>[$email,$amount]) {
    $insert->execute([$id,hash('sha256',str_repeat((string)$id,32),true),$email,$amount]);
    $db->prepare("INSERT INTO movimientos_tarjetas_regalo (id_tarjeta,tipo,monto,referencia) VALUES (?,'carga_inicial',?,?)")->execute([$id,$amount,'seed-'.$id]);
}
$checks=0;
function giftAssert(bool $value,string $message): void {global $checks;if (!$value) throw new RuntimeException($message);$checks++;}
function giftReject(callable $action,string $message): void {try {$action();} catch(DomainException $ex){giftAssert(true,$message);return;}throw new RuntimeException($message);}
giftAssert(count(ClientGiftCards::owned($db,1))===1,'Correo verificado ve regalos recibidos');
giftAssert(count(ClientGiftCards::owned($db,2))===0,'Correo no verificado no revela regalos');
giftReject(fn()=>ClientGiftCards::claim($db,2,'bad'),'Código inválido');
ClientGiftCards::claim($db,2,str_repeat('2',32));ClientGiftCards::claim($db,2,str_repeat('2',32));
giftAssert(count(ClientGiftCards::owned($db,2))===1,'Vincular código es persistente e idempotente');
giftReject(fn()=>ClientGiftCards::claim($db,1,str_repeat('2',32)),'No roba tarjeta vinculada');
giftReject(fn()=>ClientCheckout::quote($db,[1=>1],1,false,2),'No usa tarjeta ajena');
$quote=ClientCheckout::quote($db,[1=>1],1,false,1);
giftAssert($quote['total']===0 && $quote['gift_credit']===100000 && $quote['order_total']===100000,'Saldo suficiente cubre total');
$sale=ClientCheckout::order($db,1,[1=>1],'efectivo','gift-full','aprobado',0,1);
giftAssert(ClientGiftCards::owned($db,1)[0]['saldo']==='4000.00','Conserva saldo sobrante');
giftAssert($db->query("SELECT metodo FROM pagos WHERE id_venta=$sale")->fetchColumn()==='tarjeta_regalo','Registra pago real de saldo');
giftAssert(ClientCheckout::order($db,1,[1=>1],'efectivo','gift-full','aprobado',0,1)===$sale,'Reintento no duplica cobro');
giftAssert(ClientGiftCards::owned($db,1)[0]['saldo']==='4000.00','Reintento conserva saldo');
$quote=ClientCheckout::quote($db,[1=>1],2,false,2);
giftAssert($quote['total']===50000 && $quote['gift_credit']===50000,'Saldo parcial calcula restante');
$sale=ClientCheckout::order($db,2,[1=>1],'pasarela','gift-rejected','rechazado',50000,2);
giftAssert(ClientGiftCards::owned($db,2)[0]['saldo']==='500.00','Rechazo no consume regalo');
$sale=ClientCheckout::order($db,2,[1=>1],'transferencia','gift-partial','aprobado',50000,2);
giftAssert(ClientGiftCards::owned($db,2)[0]['saldo']==='0.00' && ClientGiftCards::owned($db,2)[0]['estado']==='agotada','Agota y actualiza tarjeta');
giftAssert((int)$db->query("SELECT COUNT(*) FROM pagos WHERE id_venta=$sale")->fetchColumn()===2,'Pago combinado registrado');
giftAssert($db->query("SELECT monto FROM pagos WHERE id_venta=$sale AND metodo='transferencia'")->fetchColumn()==='500.00','Pendiente solo por el restante');
giftReject(fn()=>ClientCheckout::quote($db,[1=>1],2,false,2),'Rechaza tarjeta agotada');
ClientGiftCards::claim($db,1,str_repeat('3',32));
$db->exec("UPDATE tarjetas_regalo SET fecha_emision='2020-01-01',fecha_vencimiento='2021-01-01' WHERE id_tarjeta=3");
giftReject(fn()=>ClientCheckout::quote($db,[1=>1],1,false,3),'Rechaza vencida');
ClientGiftCards::claim($db,1,str_repeat('4',32));$db->exec("UPDATE tarjetas_regalo SET estado='cancelada' WHERE id_tarjeta=4");
giftReject(fn()=>ClientCheckout::quote($db,[1=>1],1,false,4),'Rechaza cancelada');
giftReject(fn()=>ClientCheckout::order($db,1,[1=>1],'efectivo','gift-manipulated','aprobado',1,1),'Revalida importe antes de debitar');
require __DIR__.'/../app/Services/StorePromotionAdmin.php';
$admin=new StorePromotionAdmin($db);$now=new DateTimeImmutable('now',new DateTimeZone('America/Costa_Rica'));
$admin->save(['titulo'=>'Oferta test','descripcion'=>'','tipo_descuento'=>'porcentaje','valor_descuento'=>'10.00','alcance'=>'tienda','publico'=>'todos','id_grupo'=>'','productos'=>[],'categorias'=>[],'regla_minimo'=>'siempre','minimo_compra'=>'0.00','activo'=>'1','fecha_inicio'=>$now->modify('-1 day')->format('Y-m-d\TH:i'),'fecha_fin'=>$now->modify('+1 day')->format('Y-m-d\TH:i')]);
$quote=ClientCheckout::quote($db,[1=>1],1,false,1);
giftAssert($quote['discount']===10000 && $quote['gift_credit']===90000 && $quote['total']===0,'Aplica saldo después de descuentos');
$sale=ClientCheckout::order($db,1,[1=>1],'efectivo','gift-discount','aprobado',0,1);
giftAssert($db->query("SELECT total FROM ventas WHERE id_venta=$sale")->fetchColumn()==='900.00','Mantiene total contable y descuento separados del saldo');
$giftCards=ClientGiftCards::owned($db,1);$giftError=null;$giftNotice=null;$clientEndpoint='index.php';$profileMissing=false;
ob_start();require __DIR__.'/../app/Views/cliente-tarjetas.php';$html=ob_get_clean();
giftAssert(str_contains($html,'Añadir tarjeta') && str_contains($html,'Saldo disponible') && str_contains($html,'Usar en la tienda'),'Vista de regalos, vinculación y uso');
giftAssert(!str_contains($html,'codigo_hash') && !str_contains($html,str_repeat('1',32)),'No expone códigos secretos');
$cartGiftCards=$giftCards;$cartGiftId=1;$cartGiftCredit=90000;$cartPayment=true;
ob_start();require __DIR__.'/../app/Views/cliente-tarjeta-carrito.php';$html=ob_get_clean();
giftAssert(str_contains($html,'selected') && str_contains($html,'Tarjeta aplicada') && str_contains($html,'Sin tarjeta de regalo'),'Carrito permite aplicar y retirar saldo');
$insert->execute([5,hash('sha256','ABCDEF123456',true),'other@test.invalid',1000]);
$db->prepare("INSERT INTO movimientos_tarjetas_regalo (id_tarjeta,tipo,monto,referencia) VALUES (5,'carga_inicial',1000,'seed-short')")->execute();
ClientGiftCards::claim($db,1,'abcd-ef12-3456');ClientGiftCards::claim($db,1,'ABCDEF123456');
giftAssert((int)$db->query('SELECT id_cliente FROM tarjetas_regalo_clientes WHERE id_tarjeta=5')->fetchColumn()===1,'Código corto con guiones, sin guiones y minúsculas');
require __DIR__.'/../app/Models/CrudRepository.php';require __DIR__.'/../app/Services/CrudService.php';
$modules=require __DIR__.'/../config/modules.php';
$notice=(new CrudService(new CrudRepository($db,$modules['tarjetas'])))->execute('create',['id_cliente_comprador'=>'1','nombre_destinatario'=>'Luis','correo_destinatario'=>'b@test.invalid','mensaje'=>'Regalo','monto_inicial'=>'700','moneda'=>'CRC','fecha_vencimiento'=>'','estado'=>'activa'],null);
$newGift=(int)$db->query('SELECT MAX(id_tarjeta) FROM tarjetas_regalo')->fetchColumn();
giftAssert((int)$db->query('SELECT id_cliente FROM tarjetas_regalo_clientes WHERE id_tarjeta='.$newGift)->fetchColumn()===2,'Emisión asigna regalo a cuenta existente sin pedir código');
giftAssert(ClientGiftCards::credit($db,2,$newGift,100000)===70000,'Destinatario puede usar regalo asignado sin código ni correo verificado');
giftReject(fn()=>ClientGiftCards::credit($db,1,$newGift,100000),'Otra cuenta no puede utilizar el regalo asignado');
$cartGiftCards=ClientGiftCards::owned($db,2);$cartGiftId=$newGift;$cartGiftCredit=0;$storeCategory='';$storeSearch='';$storePage=1;
ob_start();require __DIR__.'/../app/Views/cliente-regalos-disponibles.php';$html=ob_get_clean();
giftAssert(str_contains($html,'tarjeta de regalo por usar') && str_contains($html,'Seleccionada') && str_contains($html,'value="0"') && !str_contains($html,'gift_code'),'Aviso superior muestra regalo y permite quitar selección sin código');
$cartGiftId=0;ob_start();require __DIR__.'/../app/Views/cliente-regalos-disponibles.php';$html=ob_get_clean();
giftAssert(str_contains($html,'Usar tarjeta') && str_contains($html,'section=tienda'),'Botón aplica regalo y permanece en tienda');
(new CrudService(new CrudRepository($db,$modules['tarjetas'])))->execute('create',['id_cliente_comprador'=>'1','nombre_destinatario'=>'Luis','correo_destinatario'=>'b@test.invalid','mensaje'=>'Regalo','monto_inicial'=>'300','moneda'=>'CRC','fecha_vencimiento'=>'','estado'=>'pendiente'],null);
$cartGiftCards=ClientGiftCards::owned($db,2);
ob_start();require __DIR__.'/../app/Views/cliente-regalos-disponibles.php';$html=ob_get_clean();
giftAssert(str_contains($html,'Pendiente de activación') && substr_count($html,'name="cart_action"')===1,'Muestra pendientes sin permitir su canje');
giftAssert(!$db->inTransaction(),'Sin transacciones abiertas');
echo "OK: $checks comprobaciones de privacidad, códigos, saldo parcial/completo, rechazo, vencimiento y reintentos. Solo tablas temporales.\n";
