<?php
declare(strict_types=1);
if (PHP_SAPI!=='cli') { http_response_code(404); exit; }
require __DIR__.'/../app/Core/bootstrap.php';
require __DIR__.'/../app/Services/ClientMembershipCheckout.php';
require __DIR__.'/../app/Services/MembershipPlans.php';
require __DIR__.'/temporary-store-promotions.php';
$db=conectarBaseDatos();
foreach (['clientes','planes_membresia','membresias_configuracion','membresias_reglas','ventas','detalle_ventas','pagos','membresias_clientes'] as $table) temporaryStoreTable($db,$table);
$db->exec("INSERT INTO clientes (id_cliente,id_cuenta,nombre,apellidos) VALUES (1,1,'Ana','Prueba'),(2,2,'Luis','Prueba'),(3,3,'Eva','Prueba')");
$db->exec("INSERT INTO planes_membresia (id_plan,nombre,precio,duracion_dias,activo) VALUES (1,'Plan prueba',1000,30,1)");
$db->exec("INSERT INTO membresias_configuracion (id_plan,nivel,cuota_mensual,cuota_anual,modalidad) VALUES (1,'esencial',1000,10000,'ambas')");
$checks=0;
function memberAssert(bool $condition,string $message): void { global $checks; if (!$condition) throw new RuntimeException($message); ++$checks; }
function memberReject(callable $action,string $message): void { try { $action(); } catch (DomainException $ex) { memberAssert(true,$message); return; } throw new RuntimeException($message); }
$q=ClientMembershipCheckout::quote($db,1,'anual');
memberAssert($q['total']===1000000 && $q['days']===365,'Precio y duración anual');
$id=ClientMembershipCheckout::order($db,1,1,'mensual','pasarela','membership-approved',100000);
$row=ClientMembershipCheckout::memberships($db,1)[0];
memberAssert($row['estado']==='activa' && $row['pago_estado']==='aprobado' && $row['total']==='1000.00','Activación con pago simulado');
memberAssert((new DateTimeImmutable($row['fecha_inicio']))->diff(new DateTimeImmutable($row['fecha_fin']))->days===30,'Duración mensual');
memberAssert(ClientMembershipCheckout::order($db,1,1,'mensual','pasarela','membership-approved',100000)===$id,'Reintento idempotente');
memberReject(fn()=>ClientMembershipCheckout::order($db,1,1,'mensual','efectivo','membership-duplicate',100000),'Evita compra duplicada con membresía vigente');
$rejected=ClientMembershipCheckout::order($db,2,1,'anual','pasarela','membership-rejected',1000000,'rechazado');
memberAssert(ClientMembershipCheckout::memberships($db,2)[0]['estado']==='cancelada','Rechazo no activa membresía');
$pending=ClientMembershipCheckout::order($db,2,1,'anual','transferencia','membership-transfer',1000000);
$row=ClientMembershipCheckout::memberships($db,2)[0];
memberAssert($row['estado']==='pendiente' && $row['pago_estado']==='pendiente' && $row['total']==='10000.00','Transferencia pendiente con cuota anual');
memberAssert((new DateTimeImmutable($row['fecha_inicio']))->diff(new DateTimeImmutable($row['fecha_fin']))->days===365,'Duración anual');
memberAssert(count(ClientMembershipCheckout::memberships($db,3))===0,'Historial restringido al cliente');
memberReject(fn()=>ClientMembershipCheckout::order($db,3,1,'mensual','efectivo','membership-price-change',1),'Rechaza precio manipulado');
memberReject(fn()=>ClientMembershipCheckout::order($db,3,1,'otro','efectivo','membership-bad-mode',100000),'Rechaza modalidad inválida');
memberReject(fn()=>ClientMembershipCheckout::order($db,3,1,'mensual','otro','membership-bad-method',100000),'Rechaza método inválido');
$db->exec("UPDATE membresias_configuracion SET modalidad='mensual'");
memberReject(fn()=>ClientMembershipCheckout::quote($db,1,'anual'),'Revalida modalidad habilitada');
$db->exec('UPDATE planes_membresia SET activo=0');
memberReject(fn()=>ClientMembershipCheckout::order($db,3,1,'mensual','efectivo','membership-disabled',100000),'Revalida plan desactivado');
$db->exec('UPDATE planes_membresia SET activo=1');
$cash=ClientMembershipCheckout::order($db,3,1,'mensual','efectivo','membership-cash',100000);
memberAssert(ClientMembershipCheckout::memberships($db,3)[0]['estado']==='pendiente','Efectivo no activa antes de verificar');
memberAssert((int)$db->query('SELECT COUNT(*) FROM ventas')->fetchColumn()===4 && (int)$db->query('SELECT COUNT(*) FROM membresias_clientes')->fetchColumn()===4,'Errores no dejan ventas o membresías parciales');
memberAssert(!$db->inTransaction(),'No quedan transacciones abiertas');
$membershipError=null;$membershipReceipt=null;$membershipQuote=ClientMembershipCheckout::quote($db,1,'mensual');
$membershipPlans=[];$membershipPlanId=1;$membershipMode='mensual';$membershipTokenKey='test_member';$_SESSION[$membershipTokenKey]='test-token';$clientEndpoint='index.php';$profileMissing=false;$clientMembershipList=[];
ob_start();require __DIR__.'/../app/Views/cliente-membresias.php';$html=ob_get_clean();
memberAssert(str_contains($html,'Confirmar suscripción') && str_contains($html,'name="expected_total" value="100000"') && str_contains($html,'name="csrf"') && str_contains($html,'sin cobro real'),'Formulario de compra con precio y protección');
$membershipReceipt=ClientMembershipCheckout::memberships($db,1)[0];
ob_start();require __DIR__.'/../app/Views/cliente-membresias.php';$html=ob_get_clean();
memberAssert(str_contains($html,'Membresía activada') && str_contains($html,'sin cobro real'),'Confirmación de activación identifica demostración');
memberReject(fn()=>ClientMembershipCheckout::cancel($db,2,$id),'No permite cancelar membresía ajena');
memberAssert(ClientMembershipCheckout::memberships($db,1)[0]['estado']==='activa','Intento ajeno conserva membresía');
ClientMembershipCheckout::cancel($db,1,$id);
$cancelled=ClientMembershipCheckout::memberships($db,1)[0];
memberAssert($cancelled['estado']==='cancelada' && $cancelled['pago_estado']==='aprobado','Cancela beneficios y conserva pago aprobado');
memberAssert($db->query("SELECT v.estado FROM ventas v JOIN detalle_ventas d ON d.id_venta=v.id_venta JOIN membresias_clientes m ON m.id_detalle_venta=d.id_detalle_venta WHERE m.id_membresia=".$id)->fetchColumn()==='completada','Conserva venta pagada');
ClientMembershipCheckout::cancel($db,1,$id);
memberAssert(count(ClientMembershipCheckout::memberships($db,1))===1,'Repetir cancelación no duplica registros');
$resub=ClientMembershipCheckout::order($db,1,1,'mensual','pasarela','membership-resubscribe',100000);
memberAssert($resub!==$id && ClientMembershipCheckout::memberships($db,1)[0]['estado']==='activa','Permite nueva suscripción después de cancelar');
ClientMembershipCheckout::cancel($db,2,$pending);
$pendingCancelled=ClientMembershipCheckout::memberships($db,2)[0];
memberAssert($pendingCancelled['estado']==='cancelada' && $pendingCancelled['pago_estado']==='cancelado','Cancela membresía y pago pendientes');
memberAssert($db->query("SELECT v.estado FROM ventas v JOIN detalle_ventas d ON d.id_venta=v.id_venta JOIN membresias_clientes m ON m.id_detalle_venta=d.id_detalle_venta WHERE m.id_membresia=".$pending)->fetchColumn()==='cancelada','Cancela pedido pendiente');
$membershipReceipt=null;$membershipQuote=null;$clientMembershipList=ClientMembershipCheckout::memberships($db,1);
ob_start();require __DIR__.'/../app/Views/cliente-membresias.php';$html=ob_get_clean();
memberAssert(str_contains($html,'Cancelar membresía') && str_contains($html,'name="confirm_cancel"') && str_contains($html,'name="membership_action" value="cancel"'),'Formulario de cancelación con confirmación');
memberAssert(!str_contains($html,'data-membership-comparison'),'Membresía vigente muestra administración en lugar de comprar otro plan');
$db->exec("INSERT INTO membresias_reglas (id_plan,codigo,valor) VALUES (1,'retoques',2),(1,'mercancia_porcentaje',15)");
$membershipPlans=(new MembershipPlans($db))->plans(true);$clientMembershipList=[];
ob_start();require __DIR__.'/../app/Views/cliente-membresias.php';$html=ob_get_clean();
memberAssert(str_contains($html,'<table class="membership-table">') && str_contains($html,'scope="row"') && str_contains($html,'name="plan"') && str_contains($html,'type="radio"'),'Comparación con beneficios por filas y selección de plan');
memberAssert(str_contains($html,'15 %') && str_contains($html,'2 sesión(es)') && str_contains($html,'✓') && str_contains($html,'No incluido'),'Expresa cantidades, descuentos e incluidos sin inventar beneficios');
memberAssert(substr_count($html,'type="submit"')===1 && str_contains($html,'Comprar membresía') && str_contains($html,'value="mensual"') && str_contains($html,'value="anual"'),'Un botón de compra con elección mensual o anual');
memberAssert(ClientMembershipCheckout::memberships($db,1)[0]['reglas']['retoques']==='2.00','Carga beneficios de membresía del cliente');
$db->exec('UPDATE planes_membresia SET activo=0');$membershipPlans=(new MembershipPlans($db))->plans(true);
ob_start();require __DIR__.'/../app/Views/cliente-membresias.php';$html=ob_get_clean();
memberAssert(!str_contains($html,'Comprar membresía') && str_contains($html,'Estamos preparando'),'No permite seleccionar planes inactivos');
memberAssert(!$db->inTransaction(),'Cancelación no deja transacciones abiertas');
echo "OK: $checks comprobaciones de compra, modalidades, activación, pendientes, rechazo, idempotencia y privacidad. Solo tablas temporales.\n";
