<?php
declare(strict_types=1);
if (PHP_SAPI!=='cli') { http_response_code(404); exit; }
require __DIR__.'/../app/Core/bootstrap.php';
require __DIR__.'/../app/Services/ClientMembershipCheckout.php';
require_once __DIR__.'/../app/Services/MembershipRenewal.php';
require_once __DIR__.'/../app/Services/MembershipPlans.php';
require __DIR__.'/temporary-store-promotions.php';
$db=conectarBaseDatos();
$db->exec(str_replace('CREATE TABLE IF NOT EXISTS','CREATE TEMPORARY TABLE',file_get_contents(__DIR__.'/../database/membresias_renovacion.sql')));
foreach (['clientes','planes_membresia','membresias_configuracion','membresias_reglas','membresias_reglas_textos','ventas','detalle_ventas','pagos','membresias_clientes'] as $table) temporaryStoreTable($db,$table);
$db->exec("INSERT INTO clientes (id_cliente,id_cuenta,nombre,apellidos) VALUES (1,1,'Ana','Prueba'),(2,2,'Luis','Prueba'),(3,3,'Eva','Prueba')");
$db->exec("INSERT INTO planes_membresia (id_plan,nombre,precio,duracion_dias,activo) VALUES (1,'Plan prueba',1000,30,1)");
$db->exec("INSERT INTO membresias_configuracion (id_plan,nivel,cuota_mensual,cuota_anual,modalidad) VALUES (1,'esencial',1000,10000,'ambas')");
$checks=0;
function memberAssert(bool $condition,string $message): void { global $checks; if (!$condition) throw new RuntimeException($message); ++$checks; }
function memberReject(callable $action,string $message): void { try { $action(); } catch (DomainException $ex) { memberAssert(true,$message); return; } throw new RuntimeException($message); }
$q=ClientMembershipCheckout::quote($db,1,'anual');
memberAssert($q['total']===1000000 && $q['days']===365,'Precio y duración anual');
$id=ClientMembershipCheckout::order($db,1,1,'mensual','pasarela','membership-approved',100000);
$row=ClientMembershipCheckout::memberships($db,1)[0];
memberAssert($row['estado']==='activa' && $row['pago_estado']==='aprobado' && $row['total']==='1000.00','Activación con pago simulado');
memberAssert((new DateTimeImmutable($row['fecha_inicio']))->diff(new DateTimeImmutable($row['fecha_fin']))->days===30,'Duración mensual');
memberAssert(ClientMembershipCheckout::order($db,1,1,'mensual','pasarela','membership-approved',100000)===$id,'Reintento idempotente');
memberReject(fn()=>ClientMembershipCheckout::order($db,1,1,'mensual','pasarela','membership-duplicate',100000),'Evita compra duplicada con membresía vigente');
$rejected=ClientMembershipCheckout::order($db,2,1,'anual','pasarela','membership-rejected',1000000,'rechazado');
memberAssert(ClientMembershipCheckout::memberships($db,2)[0]['estado']==='cancelada','Rechazo no activa membresía');
$pending=ClientMembershipCheckout::order($db,2,1,'anual','pasarela','membership-transfer',1000000);
// Existing offline memberships remain manageable after removing offline checkout.
$db->exec("UPDATE membresias_clientes SET estado='pendiente' WHERE id_membresia=".$pending);
$db->exec("UPDATE pagos SET metodo='transferencia',estado='pendiente' WHERE clave_idempotencia='membership-transfer'");
$row=ClientMembershipCheckout::memberships($db,2)[0];
memberAssert($row['estado']==='pendiente' && $row['pago_estado']==='pendiente' && $row['total']==='10000.00','Transferencia pendiente con cuota anual');
memberAssert((new DateTimeImmutable($row['fecha_inicio']))->diff(new DateTimeImmutable($row['fecha_fin']))->days===365,'Duración anual');
memberAssert(count(ClientMembershipCheckout::memberships($db,3))===0,'Historial restringido al cliente');
memberReject(fn()=>ClientMembershipCheckout::order($db,3,1,'mensual','pasarela','membership-price-change',1),'Rechaza precio manipulado');
memberReject(fn()=>ClientMembershipCheckout::order($db,3,1,'otro','pasarela','membership-bad-mode',100000),'Rechaza modalidad inválida');
memberReject(fn()=>ClientMembershipCheckout::order($db,3,1,'mensual','otro','membership-bad-method',100000),'Rechaza método inválido');
$db->exec("UPDATE membresias_configuracion SET modalidad='mensual'");
memberReject(fn()=>ClientMembershipCheckout::quote($db,1,'anual'),'Revalida modalidad habilitada');
$db->exec('UPDATE planes_membresia SET activo=0');
memberReject(fn()=>ClientMembershipCheckout::order($db,3,1,'mensual','pasarela','membership-disabled',100000),'Revalida plan desactivado');
$db->exec('UPDATE planes_membresia SET activo=1');
$cash=ClientMembershipCheckout::order($db,3,1,'mensual','pasarela','membership-cash',100000);
$db->exec("UPDATE membresias_clientes SET estado='pendiente' WHERE id_membresia=".$cash);
$db->exec("UPDATE pagos SET metodo='efectivo',estado='pendiente' WHERE clave_idempotencia='membership-cash'");
memberAssert(ClientMembershipCheckout::memberships($db,3)[0]['estado']==='pendiente','Efectivo no activa antes de verificar');
memberAssert((int)$db->query('SELECT COUNT(*) FROM ventas')->fetchColumn()===4 && (int)$db->query('SELECT COUNT(*) FROM membresias_clientes')->fetchColumn()===4,'Errores no dejan ventas o membresías parciales');
memberAssert(!$db->inTransaction(),'No quedan transacciones abiertas');
foreach (['efectivo','transferencia'] as $offlineMethod) memberReject(fn()=>ClientMembershipCheckout::order($db,3,1,'mensual',$offlineMethod,'blocked-'.$offlineMethod,100000),'Rechaza nuevos pagos fuera de tarjeta');
$membershipError=null;$membershipReceipt=null;$membershipQuote=ClientMembershipCheckout::quote($db,1,'mensual');
$membershipPlans=[];$membershipPlanId=1;$membershipMode='mensual';$membershipTokenKey='test_member';$_SESSION[$membershipTokenKey]='test-token';$clientEndpoint='index.php';$profileMissing=false;$clientMembershipList=[];
$publicPrefix='';
ob_start();require __DIR__.'/../app/Views/cliente-membresias.php';$html=ob_get_clean();
memberAssert(str_contains($html,'Confirmar suscripción') && str_contains($html,'name="expected_total" value="100000"') && str_contains($html,'name="csrf"') && str_contains($html,'sin cobro real'),'Formulario de compra con precio y protección');
memberAssert(str_contains($html,'name="payment_method" value="pasarela"') && !str_contains($html,'value="efectivo"') && !str_contains($html,'value="transferencia"'),'Formulario ofrece únicamente tarjeta');
$membershipReceipt=ClientMembershipCheckout::memberships($db,1)[0];
ob_start();require __DIR__.'/../app/Views/cliente-membresias.php';$html=ob_get_clean();
memberAssert(str_contains($html,'Membresía activada') && str_contains($html,'sin cobro real'),'Confirmación de activación identifica demostración');
memberReject(fn()=>ClientMembershipCheckout::cancel($db,2,$id),'No permite cancelar membresía ajena');
memberAssert(ClientMembershipCheckout::memberships($db,1)[0]['estado']==='activa','Intento ajeno conserva membresía');
ClientMembershipCheckout::cancel($db,1,$id);
$cancelled=ClientMembershipCheckout::memberships($db,1)[0];
memberAssert($cancelled['estado']==='cancelada' && $cancelled['pago_estado']==='aprobado','Cancela beneficios y conserva pago aprobado');
memberAssert($db->query("SELECT v.estado FROM ventas v JOIN detalle_ventas d ON d.id_venta=v.id_venta JOIN membresias_clientes m ON m.id_detalle_venta=d.id_detalle_venta WHERE m.id_membresia=".$id)->fetchColumn()==='completada','Conserva venta pagada');
ClientMembershipCheckout::cancel($db,1,$id);
memberAssert(count(ClientMembershipCheckout::memberships($db,1))===1,'Repetir cancelación no duplica registros');
$resub=ClientMembershipCheckout::order($db,1,1,'mensual','pasarela','membership-resubscribe',100000);
memberAssert($resub!==$id && ClientMembershipCheckout::memberships($db,1)[0]['estado']==='activa','Permite nueva suscripción después de cancelar');
ClientMembershipCheckout::cancel($db,2,$pending);
$pendingCancelled=ClientMembershipCheckout::memberships($db,2)[0];
memberAssert($pendingCancelled['estado']==='cancelada' && $pendingCancelled['pago_estado']==='cancelado','Cancela membresía y pago pendientes');
memberAssert($db->query("SELECT v.estado FROM ventas v JOIN detalle_ventas d ON d.id_venta=v.id_venta JOIN membresias_clientes m ON m.id_detalle_venta=d.id_detalle_venta WHERE m.id_membresia=".$pending)->fetchColumn()==='cancelada','Cancela pedido pendiente');
$membershipReceipt=null;$membershipQuote=null;$clientMembershipList=ClientMembershipCheckout::memberships($db,1);
ob_start();require __DIR__.'/../app/Views/cliente-membresias.php';$html=ob_get_clean();
memberAssert(str_contains($html,'Cancelar membresía') && str_contains($html,'name="confirm_cancel"') && str_contains($html,'name="membership_action" value="cancel"'),'Formulario de cancelación con confirmación');
memberAssert(!str_contains($html,'data-membership-comparison'),'Membresía vigente muestra administración en lugar de comprar otro plan');
$db->exec("INSERT INTO membresias_reglas (id_plan,codigo,valor) VALUES (1,'retoques',2),(1,'mercancia_porcentaje',15)");
$membershipPlans=(new MembershipPlans($db))->plans(true);$clientMembershipList=[];
ob_start();require __DIR__.'/../app/Views/cliente-membresias.php';$html=ob_get_clean();
memberAssert(str_contains($html,'<table class="membership-table">') && str_contains($html,'scope="row"') && str_contains($html,'name="plan"') && str_contains($html,'type="radio"'),'Comparación con beneficios por filas y selección de plan');
memberAssert(str_contains($html,'15 %') && str_contains($html,'2 sesión(es)') && str_contains($html,'✓') && str_contains($html,'No incluido'),'Expresa cantidades, descuentos e incluidos sin inventar beneficios');
memberAssert(substr_count($html,'type="submit"')===1 && str_contains($html,'Comprar membresía') && str_contains($html,'value="mensual"') && str_contains($html,'value="anual"'),'Un botón de compra con elección mensual o anual');
memberAssert(ClientMembershipCheckout::memberships($db,1)[0]['reglas']['retoques']==='2.00','Carga beneficios de membresía del cliente');
$db->exec('UPDATE planes_membresia SET activo=0');$membershipPlans=(new MembershipPlans($db))->plans(true);
ob_start();require __DIR__.'/../app/Views/cliente-membresias.php';$html=ob_get_clean();
memberAssert(!str_contains($html,'Comprar membresía') && str_contains($html,'Estamos preparando'),'No permite seleccionar planes inactivos');
memberAssert(!$db->inTransaction(),'Cancelación no deja transacciones abiertas');
$db->exec("UPDATE membresias_clientes SET fecha_inicio=UTC_TIMESTAMP()-INTERVAL 31 DAY,fecha_fin=UTC_TIMESTAMP() WHERE id_membresia=".$resub);
$expired=ClientMembershipCheckout::memberships($db,1)[0];
memberAssert($expired['estado']==='vencida','Vence exactamente al terminar el período');
memberAssert($db->query('SELECT estado FROM membresias_clientes WHERE id_membresia='.$resub)->fetchColumn()==='vencida','Persiste el vencimiento');
memberAssert($db->query('SELECT estado FROM membresias_clientes WHERE id_membresia='.$id)->fetchColumn()==='cancelada','El vencimiento conserva cancelaciones anteriores');
memberReject(fn()=>ClientMembershipCheckout::cancel($db,1,$resub),'No convierte una vencida en cancelada');
$db->exec('UPDATE planes_membresia SET activo=1');
$renewed=ClientMembershipCheckout::order($db,1,1,'mensual','pasarela','membership-renew-after-expiry',100000);
memberAssert($renewed!==$resub && ClientMembershipCheckout::memberships($db,1)[0]['estado']==='activa','Nueva compra activa otro período y conserva el vencido');
$db->exec("UPDATE membresias_clientes SET estado='pendiente' WHERE id_membresia=".$renewed);
memberAssert(ClientMembershipCheckout::memberships($db,1)[0]['estado']==='activa','Pago aprobado activa período vigente pendiente');
ClientMembershipCheckout::cancel($db,1,$renewed);
memberAssert(ClientMembershipCheckout::memberships($db,1)[0]['estado']==='cancelada','Pago aprobado no reactiva una membresía cancelada');
$clientMembershipList=ClientMembershipCheckout::memberships($db,1);$membershipPlans=(new MembershipPlans($db))->plans(true);
ob_start();require __DIR__.'/../app/Views/cliente-membresias.php';$historyHtml=ob_get_clean();
memberAssert(!str_contains($historyHtml,'Historial de mis membresías') && str_contains($historyHtml,'Comprar membresía'),'Oculta historial y permite continuar con otro período');
$auto=ClientMembershipCheckout::order($db,1,1,'mensual','pasarela','auto-initial',100000);
memberReject(fn()=>MembershipRenewal::configure($db,1,$auto,true,false,'aprobado'),'Exige aceptación de condiciones');
memberReject(fn()=>MembershipRenewal::configure($db,2,$auto,true,true,'aprobado'),'No configura membresía ajena');
MembershipRenewal::configure($db,1,$auto,true,true,'aprobado');
memberAssert(MembershipRenewal::settings($db,$auto)['terminos_version']===MembershipRenewal::TERMS,'Registra aceptación de términos');
$db->exec("UPDATE membresias_clientes SET fecha_inicio=UTC_TIMESTAMP()-INTERVAL 31 DAY,fecha_fin=UTC_TIMESTAMP()-INTERVAL 1 DAY WHERE id_membresia=".$auto);
$before=(int)$db->query('SELECT COUNT(*) FROM pagos')->fetchColumn();
$db->exec('UPDATE membresias_configuracion SET cuota_mensual=1500');
MembershipRenewal::process($db,1);
$autoRow=ClientMembershipCheckout::memberships($db,1)[0];
memberAssert($autoRow['estado']==='activa' && $autoRow['total']==='1000.00','Renueva automáticamente al precio autorizado');
memberAssert((int)$db->query('SELECT COUNT(*) FROM pagos')->fetchColumn()===$before+1,'Registra un pago de renovación');
MembershipRenewal::process($db,1);
memberAssert((int)$db->query('SELECT COUNT(*) FROM pagos')->fetchColumn()===$before+1,'Procesar de nuevo no duplica el cobro');
MembershipRenewal::configure($db,1,$auto,false,false,'aprobado');
memberAssert(ClientMembershipCheckout::memberships($db,1)[0]['estado']==='activa','Desactivar renovación conserva período pagado');
MembershipRenewal::configure($db,1,$auto,true,true,'rechazado');
$db->exec("UPDATE membresias_clientes SET fecha_inicio=UTC_TIMESTAMP()-INTERVAL 31 DAY,fecha_fin=UTC_TIMESTAMP()-INTERVAL 1 DAY WHERE id_membresia=".$auto);
MembershipRenewal::process($db,1);
memberAssert(ClientMembershipCheckout::memberships($db,1)[0]['estado']==='vencida' && !MembershipRenewal::settings($db,$auto)['habilitada'],'Rechazo vence y detiene reintentos');
$auto2=ClientMembershipCheckout::order($db,1,1,'mensual','pasarela','auto-cancel',150000);
MembershipRenewal::configure($db,1,$auto2,true,true,'aprobado');
ClientMembershipCheckout::cancel($db,1,$auto2);
memberAssert(!MembershipRenewal::settings($db,$auto2)['habilitada'],'Cancelar membresía detiene renovación');
memberReject(fn()=>ClientMembershipCheckout::order($db,1,1,'mensual','pasarela','purchase-no-consent',150000,'aprobado',true,false),'Compra exige consentimiento para renovar');
$atPurchase=ClientMembershipCheckout::order($db,1,1,'mensual','pasarela','purchase-renewal',150000,'aprobado',true,true);
memberAssert((bool)MembershipRenewal::settings($db,$atPurchase)['habilitada'],'Compra y renovación se registran juntas');
memberAssert(ClientMembershipCheckout::order($db,1,1,'mensual','pasarela','purchase-renewal',150000,'aprobado',true,true)===$atPurchase,'Reintento de compra no duplica renovación');
$clientMembershipList=ClientMembershipCheckout::memberships($db,1);
$clientMembershipList[0]['renovacion']=MembershipRenewal::settings($db,$atPurchase);
ob_start();require __DIR__.'/../app/Views/cliente-membresias.php';$activeHtml=ob_get_clean();
memberAssert(!str_contains($activeHtml,'name="accept_renewal_terms"') && str_contains($activeHtml,'Desactivar renovación'),'Membresía activa solo permite desactivar renovación');
$clientMembershipList=[];$membershipQuote=ClientMembershipCheckout::quote($db,1,'mensual');
ob_start();require __DIR__.'/../app/Views/cliente-membresias.php';$purchaseHtml=ob_get_clean();
memberAssert(str_contains($purchaseHtml,'Términos y condiciones') && str_contains($purchaseHtml,'name="accept_renewal_terms"'),'Condiciones y consentimiento aparecen al comprar');
echo "OK: $checks comprobaciones de compra, modalidades, activación, pendientes, rechazo, idempotencia y privacidad. Solo tablas temporales.\n";
