<?php
// Lista cerrada: ningún nombre de tabla o columna procede directamente del navegador.
return [
    'cuentas' => ['title'=>'Cuentas de usuarios','table'=>'cuentas','pk'=>['id_cuenta'],'group'=>'Cuentas','hidden'=>['contrasena_hash']],
    'categorias' => ['title' => 'Categorías de tatuajes', 'table' => 'categorias_tatuajes', 'pk' => ['id_categoria'], 'group' => 'Categorías / filtros'],
    'especialidades' => ['title' => 'Especialidades de artistas', 'table' => 'artistas_especialidades', 'pk' => ['id_artista', 'id_categoria'], 'group' => 'Categorías / filtros'],
'calificaciones' => [
    'title' => 'Calificaciones de artistas',
    'table' => 'calificaciones_artistas',
    'pk' => ['id_calificacion'],
    'group' => 'Calificaciones',
    'readonly' => true,
],    'resumen_calificaciones' => ['title' => 'Promedios por artista', 'table' => 'vista_calificaciones_artistas', 'pk' => ['id_artista'], 'group' => 'Calificaciones', 'readonly' => true],
    'promociones' => ['title' => 'Ofertas y promociones', 'table' => 'promociones', 'pk' => ['id_promocion'], 'group' => 'Ofertas'],
    'planes' => ['title' => 'Planes de membresía', 'table' => 'planes_membresia', 'pk' => ['id_plan'], 'group' => 'Membresía'],
    'membresias' => ['title' => 'Membresías de clientes', 'table' => 'membresias_clientes', 'pk' => ['id_membresia'], 'group' => 'Membresía'],
    'beneficios' => ['title' => 'Vista general de beneficios', 'table' => 'beneficios', 'pk' => ['id_beneficio'], 'group' => 'Beneficios', 'readonly' => true],
    'planes_beneficios' => ['title' => 'Beneficios por plan', 'table' => 'planes_beneficios', 'pk' => ['id_plan', 'id_beneficio'], 'group' => 'Membresía'],
    'tarjetas' => ['title' => 'Tarjetas de regalo', 'table' => 'tarjetas_regalo', 'pk' => ['id_tarjeta'], 'group' => 'Tarjetas de regalo', 'hidden' => ['codigo_hash','id_detalle_venta']],
    'movimientos' => ['title' => 'Movimientos de tarjetas', 'table' => 'movimientos_tarjetas_regalo', 'pk' => ['id_movimiento'], 'group' => 'Tarjetas de regalo', 'readonly' => true],
    'saldos_tarjetas' => ['title' => 'Saldos de tarjetas', 'table' => 'vista_saldo_tarjetas', 'pk' => ['id_tarjeta'], 'group' => 'Tarjetas de regalo', 'readonly' => true],
    'categorias_productos' => ['title' => 'Categorías de artículos', 'table' => 'categorias_productos', 'pk' => ['id_categoria_producto'], 'group' => 'Venta de artículos'],
    'productos' => ['title' => 'Artículos e inventario', 'table' => 'productos', 'pk' => ['id_producto'], 'group' => 'Venta de artículos'],
    'imagenes' => ['title' => 'Imágenes de artículos', 'table' => 'imagenes_productos', 'pk' => ['id_imagen'], 'group' => 'Venta de artículos'],
    'ventas' => ['title' => 'Ventas', 'table' => 'ventas', 'pk' => ['id_venta'], 'group' => 'Venta de artículos', 'computed' => ['subtotal', 'descuento_total', 'impuesto_total']],
    'detalle' => ['title' => 'Detalle de ventas', 'table' => 'detalle_ventas', 'pk' => ['id_detalle_venta'], 'group' => 'Venta de artículos'],
    'promociones_tienda' => ['title'=>'Promociones y ofertas', 'table'=>'promociones', 'pk'=>['id_promocion'], 'group'=>'Venta de artículos'],
    'grupos_clientes' => ['title'=>'Grupos de clientes', 'table'=>'grupos_clientes', 'pk'=>['id_grupo'], 'group'=>'Venta de artículos'],
    'clientes_grupos' => ['title'=>'Clientes por grupo', 'table'=>'clientes_grupos', 'pk'=>['id_grupo','id_cliente'], 'group'=>'Venta de artículos'],
];
