<ol class="pasos-compra" aria-label="Proceso de compra"><li><span>1</span> Carrito</li><li><span>2</span> Pago</li><li aria-current="step"><span>3</span> Confirmación</li></ol>
<section class="card confirmacion-compra shadow-sm">
    <div class="confirmacion-icono" aria-hidden="true">✓</div>
    <p class="eyebrow">PEDIDO REGISTRADO</p>
    <h2><?= $cartReceipt['metodo']==='tarjeta_regalo'?'Pedido pagado con tarjeta de regalo':($cartReceipt['metodo']==='sin_cobro'?'Pedido confirmado sin pago':($cartReceipt['estado']==='aprobado'?'Compra de demostración completada':'Tu pedido está reservado')) ?></h2>
    <p><?= $cartReceipt['metodo']==='tarjeta_regalo'?'Se descontó el importe del saldo de tu tarjeta. Retira tus artículos en el estudio.':($cartReceipt['metodo']==='sin_cobro'?'La promoción cubrió el total. Retira tus artículos en el estudio.':($cartReceipt['estado']==='aprobado'?((float)($cartReceipt['gift_credit']??0)>0?'El saldo de regalo se descontó. El pago restante con tarjeta fue simulado, sin cobro externo.':'La tarjeta de prueba fue aprobada. No se realizó ningún cobro real.'):'El pago restante está pendiente de verificación. Coordina el retiro y pago con el estudio.')) ?></p>
    <?php if ((float)($cartReceipt['gift_credit']??0)>0): ?><p>Pagado con tarjeta de regalo: <strong>₡<?= e(number_format((float)$cartReceipt['gift_credit'],2,',','.')) ?></strong><?php if ($cartReceipt['metodo']!=='tarjeta_regalo'): ?> · Pago restante: ₡<?= e(number_format((float)$cartReceipt['remaining_payment'],2,',','.')) ?><?php endif ?></p><?php endif ?>
    <div class="pago-resumen-compacto"><div><span>Método de pago</span><strong><?= e(['efectivo'=>'Efectivo al retirar','transferencia'=>'Transferencia','pasarela'=>'Tarjeta de demostración','sin_cobro'=>'Cubierto por promoción'][$cartReceipt['metodo']]??label($cartReceipt['metodo'])) ?></strong></div><div><span>Total del pedido</span><strong>₡<?= e(number_format((float)$cartReceipt['total'],2,',','.')) ?></strong></div></div>
    <?php if ((float)($cartReceipt['descuento_total']??0)>0): ?><p>Descuento incluido: ₡<?= e(number_format((float)$cartReceipt['descuento_total'],2,',','.')) ?></p><?php endif ?>
    <div class="row g-3 confirmacion-detalles"><div class="col-12 col-sm-6"><span>Estado del pago</span><strong><?= e(label($cartReceipt['estado'])) ?></strong></div><div class="col-12 col-sm-6"><span>Entrega</span><strong>Retiro en el estudio</strong></div></div>
</section>
<?php $checkoutBarStep='confirmacion';$checkoutBarTotal=(float)$cartReceipt['total'];$checkoutBarInfo='Pedido registrado';require __DIR__.'/cliente-compra-barra.php'; ?>
